# Implied Volatility Surface
# Compute and visualise the implied volatility surface generated by the Heston stochastic volatility model
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import griddata

from heston import analytical_call_price
from black_scholes import implied_volatility

# ---Surface computation---
# Compute implied volatility surface under the Heston model
def heston_iv_surface(S0: float, v0: float, kappa: float, theta: float,
                      xi: float, rho: float, r: float,
                      strikes: np.ndarray, maturities: np.ndarray) -> np.ndarray:
    IV = np.full((len(maturities), len(strikes)), np.nan)

    for i, T in enumerate(maturities):
        for j, K in enumerate(strikes):
            price = analytical_call_price(S0, v0, kappa, theta, xi, rho, r, T, K)
            IV[i, j] = implied_volatility(price, S0, K, T, r, option="call")

    # Interpolate NaN values (deep ITM/OTM where BS inversion fails)
    mask = np.isnan(IV)
    if mask.any():
        K_grid, T_grid = np.meshgrid(strikes, maturities)
        valid  = ~mask
        points = np.column_stack([K_grid[valid], T_grid[valid]])
        values = IV[valid]
        IV[mask] = griddata(points, values,
                            (K_grid[mask], T_grid[mask]), method="nearest")

    return IV

# ---Visualisation---
# Plot implied volatility surface as a 3D mesh
def plot_surface(IV: np.ndarray, strikes: np.ndarray, maturities: np.ndarray,
                 title: str = "Heston Model — Implied Volatility Surface",
                 save_path: str = None) -> None:
    K_grid, T_grid = np.meshgrid(strikes, maturities)
    IV_pct = np.ma.masked_invalid(IV * 100)

    fig = plt.figure(figsize=(12, 7))
    ax  = fig.add_subplot(111, projection="3d")
    surf = ax.plot_surface(K_grid, T_grid, IV_pct, cmap="viridis", alpha=0.85)

    ax.set_title(title, fontsize=14, pad=15)
    ax.set_xlabel("Strike (K)")
    ax.set_ylabel("Maturity (years)")
    ax.set_zlabel("Implied Volatility (%)")
    fig.colorbar(surf, ax=ax, shrink=0.5, label="IV (%)")

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()

# Plot volatility smile for selected maturities
def plot_smile(IV: np.ndarray, strikes: np.ndarray, maturities: np.ndarray,
               maturity_indices: list = None, save_path: str = None) -> None:
    if maturity_indices is None:
        maturity_indices = list(range(len(maturities)))

    fig, ax = plt.subplots(figsize=(10, 6))
    for idx in maturity_indices:
        ax.plot(strikes, IV[idx] * 100, lw=2, label=f"T = {maturities[idx]:.2f}y")

    ax.set_title("Volatility Smile — Heston Model", fontsize=14)
    ax.set_xlabel("Strike (K)")
    ax.set_ylabel("Implied Volatility (%)")
    ax.legend()
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=150, bbox_inches="tight")
    plt.show()